version: 0.0
os: linux
files:
  - source: /target/universal/test-app-1.0-SNAPSHOT.tgz
    destination: /home/ec2-user/play-app
  - source: scripts/stop-server.sh
    destination: /home/ec2-user/play-app/scripts
  - source: scripts/start-server.sh
    destination: /home/ec2-user/play-app/scripts
  - source: scripts/setup.sh
    destination: /home/ec2-user/play-app/scripts
  
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      runas: root
  AfterInstall:
    - location: scripts/setup.sh
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: root

