version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/play-app
#hooks:
  #ApplicationStop:
    #- location: scripts/stop_service.sh
      #runas: root
  #ApplicationStart:
    #- location: scripts/start_service.sh
      #runas: root
  #BeforeInstall:
    #- location: scripts/cleanup.sh
      #runas: root
